modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: employment_capacity
    alt_filters: null
    alt_sample_size: 5
    alternatives: blocks
    choice_column: null
    chooser_filters: null
    chooser_sample_size: null
    chooser_size: null
    choosers: null
    constrained_choices: true
    fitted_parameters:
    - -1.9001051370818296
    - -0.04875149550594825
    - -2.559103901016961
    - 0.8565036939349113
    - 6.540366631512698
    - 1.3877578811699653
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        extra_obs_cols:
        - home_taz
        successive_merges:
        -   how: left
            left_on:
            - home_taz
            - zone_id
            right_cols:
            - logsum
            - tour_sov_in_vehicle_time
            - tour_dist
            right_index: true
            right_table: travel_data
        aggregations: null
        rename_cols: null
    model_expression: logsum + tour_sov_in_vehicle_time + np.log1p(tour_dist) + logsum:np.log1p(tour_dist)
        +pct_sector_tech:taz_pct_no_higher_ed + logsum:taz_pct_hh_inc_under_25k -
        1
    name: wlcm
    out_alt_filters: null
    out_alternatives: null
    out_chooser_filters:
    - worker == 1
    - work_at_home == 0
    out_choosers: persons
    out_column: work_block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         10,000\nModel:\
        \         Multinomial Logit   Df Residuals:              9,994\nMethod:  \
        \     Maximum Likelihood   Df Model:                      6\nDate:       \
        \          2023-06-26   Pseudo R-squ.:             0.294\nTime:          \
        \            08:06   Pseudo R-bar-squ.:         0.294\nAIC:              \
        \    65,003.948   Log-Likelihood:      -32,495.974\nBIC:                 \
        \ 65,047.210   LL-Null:             -46,051.702\n=========================================================================================\n\
        \                                          coef   std err         z     P>|z|\
        \   Conf. Int.\n-----------------------------------------------------------------------------------------\n\
        logsum                                 -1.9001     0.040   -47.780     0.000\
        \             \ntour_sov_in_vehicle_time               -0.0488     0.019 \
        \   -2.615     0.009             \nnp.log1p(tour_dist)                   \
        \ -2.5591     0.028   -90.637     0.000             \nlogsum:np.log1p(tour_dist)\
        \              0.8565     0.018    47.218     0.000             \npct_sector_tech:taz_pct_no_higher_ed\
        \    6.5404     0.180    36.279     0.000             \nlogsum:taz_pct_hh_inc_under_25k\
        \         1.3878     0.071    19.471     0.000             \n========================================================================================="
    tags:
    - juan
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
